/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.chilkatsoft;

public class CkOmaDrm {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CkOmaDrm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CkOmaDrm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        chilkatJNI.delete_CkOmaDrm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CkOmaDrm() {
    this(chilkatJNI.new_CkOmaDrm(), true);
  }

  public void LastErrorXml(CkString str) {
    chilkatJNI.CkOmaDrm_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorHtml(CkString str) {
    chilkatJNI.CkOmaDrm_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void LastErrorText(CkString str) {
    chilkatJNI.CkOmaDrm_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public void get_LastErrorHtml(CkString str) {
    chilkatJNI.CkOmaDrm_get_LastErrorHtml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorHtml() {
    return chilkatJNI.CkOmaDrm_lastErrorHtml(swigCPtr, this);
  }

  public void get_LastErrorText(CkString str) {
    chilkatJNI.CkOmaDrm_get_LastErrorText(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorText() {
    return chilkatJNI.CkOmaDrm_lastErrorText(swigCPtr, this);
  }

  public void get_LastErrorXml(CkString str) {
    chilkatJNI.CkOmaDrm_get_LastErrorXml(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String lastErrorXml() {
    return chilkatJNI.CkOmaDrm_lastErrorXml(swigCPtr, this);
  }

  public void get_Version(CkString str) {
    chilkatJNI.CkOmaDrm_get_Version(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String version() {
    return chilkatJNI.CkOmaDrm_version(swigCPtr, this);
  }

  public void get_DebugLogFilePath(CkString str) {
    chilkatJNI.CkOmaDrm_get_DebugLogFilePath(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String debugLogFilePath() {
    return chilkatJNI.CkOmaDrm_debugLogFilePath(swigCPtr, this);
  }

  public void put_DebugLogFilePath(String newVal) {
    chilkatJNI.CkOmaDrm_put_DebugLogFilePath(swigCPtr, this, newVal);
  }

  public boolean get_VerboseLogging() {
    return chilkatJNI.CkOmaDrm_get_VerboseLogging(swigCPtr, this);
  }

  public void put_VerboseLogging(boolean newVal) {
    chilkatJNI.CkOmaDrm_put_VerboseLogging(swigCPtr, this, newVal);
  }

  public boolean get_LastMethodSuccess() {
    return chilkatJNI.CkOmaDrm_get_LastMethodSuccess(swigCPtr, this);
  }

  public void put_LastMethodSuccess(boolean newVal) {
    chilkatJNI.CkOmaDrm_put_LastMethodSuccess(swigCPtr, this, newVal);
  }

  public boolean SaveLastError(String path) {
    return chilkatJNI.CkOmaDrm_SaveLastError(swigCPtr, this, path);
  }

  public void get_Base64Key(CkString str) {
    chilkatJNI.CkOmaDrm_get_Base64Key(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String base64Key() {
    return chilkatJNI.CkOmaDrm_base64Key(swigCPtr, this);
  }

  public void put_Base64Key(String newVal) {
    chilkatJNI.CkOmaDrm_put_Base64Key(swigCPtr, this, newVal);
  }

  public void get_ContentType(CkString str) {
    chilkatJNI.CkOmaDrm_get_ContentType(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String contentType() {
    return chilkatJNI.CkOmaDrm_contentType(swigCPtr, this);
  }

  public void put_ContentType(String newVal) {
    chilkatJNI.CkOmaDrm_put_ContentType(swigCPtr, this, newVal);
  }

  public void get_ContentUri(CkString str) {
    chilkatJNI.CkOmaDrm_get_ContentUri(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String contentUri() {
    return chilkatJNI.CkOmaDrm_contentUri(swigCPtr, this);
  }

  public void put_ContentUri(String newVal) {
    chilkatJNI.CkOmaDrm_put_ContentUri(swigCPtr, this, newVal);
  }

  public void get_DecryptedData(CkByteData outBytes) {
    chilkatJNI.CkOmaDrm_get_DecryptedData(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public int get_DrmContentVersion() {
    return chilkatJNI.CkOmaDrm_get_DrmContentVersion(swigCPtr, this);
  }

  public void get_EncryptedData(CkByteData outBytes) {
    chilkatJNI.CkOmaDrm_get_EncryptedData(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public void get_Headers(CkString str) {
    chilkatJNI.CkOmaDrm_get_Headers(swigCPtr, this, CkString.getCPtr(str), str);
  }

  public String headers() {
    return chilkatJNI.CkOmaDrm_headers(swigCPtr, this);
  }

  public void put_Headers(String newVal) {
    chilkatJNI.CkOmaDrm_put_Headers(swigCPtr, this, newVal);
  }

  public void get_IV(CkByteData outBytes) {
    chilkatJNI.CkOmaDrm_get_IV(swigCPtr, this, CkByteData.getCPtr(outBytes), outBytes);
  }

  public void put_IV(CkByteData inBytes) {
    chilkatJNI.CkOmaDrm_put_IV(swigCPtr, this, CkByteData.getCPtr(inBytes), inBytes);
  }

  public boolean CreateDcfFile(String filename) {
    return chilkatJNI.CkOmaDrm_CreateDcfFile(swigCPtr, this, filename);
  }

  public boolean GetHeaderField(String fieldName, CkString outVal) {
    return chilkatJNI.CkOmaDrm_GetHeaderField(swigCPtr, this, fieldName, CkString.getCPtr(outVal), outVal);
  }

  public String getHeaderField(String fieldName) {
    return chilkatJNI.CkOmaDrm_getHeaderField(swigCPtr, this, fieldName);
  }

  public String headerField(String fieldName) {
    return chilkatJNI.CkOmaDrm_headerField(swigCPtr, this, fieldName);
  }

  public boolean LoadDcfData(CkByteData data) {
    return chilkatJNI.CkOmaDrm_LoadDcfData(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadDcfFile(String filename) {
    return chilkatJNI.CkOmaDrm_LoadDcfFile(swigCPtr, this, filename);
  }

  public void LoadUnencryptedData(CkByteData data) {
    chilkatJNI.CkOmaDrm_LoadUnencryptedData(swigCPtr, this, CkByteData.getCPtr(data), data);
  }

  public boolean LoadUnencryptedFile(String filename) {
    return chilkatJNI.CkOmaDrm_LoadUnencryptedFile(swigCPtr, this, filename);
  }

  public boolean SaveDecrypted(String filename) {
    return chilkatJNI.CkOmaDrm_SaveDecrypted(swigCPtr, this, filename);
  }

  public void SetEncodedIV(String encodedIv, String encoding) {
    chilkatJNI.CkOmaDrm_SetEncodedIV(swigCPtr, this, encodedIv, encoding);
  }

  public boolean UnlockComponent(String unlockCode) {
    return chilkatJNI.CkOmaDrm_UnlockComponent(swigCPtr, this, unlockCode);
  }

}
